import Link from 'next/link';
import { useEffect, useState } from 'react';
import AdminLayout from '../../components/AdminLayout';
import { requireAdmin } from '../../lib/adminAuth';

export async function getServerSideProps({ req, res }) { const auth = await requireAdmin(req, res); if (!auth.ok) return { redirect: { destination: auth.status === 401 ? '/signin?next=/admin/settings' : '/admin', permanent: false } }; return { props: {} }; }

export default function AdminSettings() {
  const [form, setForm] = useState({ firstName: '', lastName: '', phone: '' }); const [email, setEmail] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState(''); const [error, setError] = useState('');
  useEffect(() => { fetch('/api/admin/settings').then(async r => { const data = await r.json(); if (!r.ok) throw new Error(data.error); setForm({ firstName: data.profile.first_name || '', lastName: data.profile.last_name || '', phone: data.profile.phone || '' }); setEmail(data.email || ''); }).catch(e => setError(e.message)).finally(() => setLoading(false)); }, []);
  function update(name, value) { setForm(current => ({ ...current, [name]: value })); setNotice(''); setError(''); }
  async function save(event) { event.preventDefault(); setSaving(true); setNotice(''); setError(''); try { const r = await fetch('/api/admin/settings', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const data = await r.json(); if (!r.ok) throw new Error(data.error); setForm({ firstName: data.profile.first_name || '', lastName: data.profile.last_name || '', phone: data.profile.phone || '' }); setNotice('Your administrator profile has been saved.'); } catch (e) { setError(e.message); } finally { setSaving(false); } }
  return <AdminLayout title="Settings" description="Manage your administrator profile and workspace access."><div className="admin-settings-grid"><section className="admin-panel admin-settings-card"><div className="admin-panel-heading"><div><span className="admin-overline">Administrator profile</span><h3>Personal details</h3></div><span className="admin-settings-badge"><i className="fa-solid fa-shield-halved" /> Admin</span></div>{loading ? <p className="admin-muted">Loading settings…</p> : <form onSubmit={save} className="admin-form-compact"><div className="admin-form-grid"><label className="admin-field"><span>First name</span><input value={form.firstName} onChange={e => update('firstName', e.target.value)} required /></label><label className="admin-field"><span>Last name</span><input value={form.lastName} onChange={e => update('lastName', e.target.value)} required /></label></div><label className="admin-field"><span>Email address</span><input value={email} readOnly disabled /></label><label className="admin-field"><span>Phone number</span><input value={form.phone} onChange={e => update('phone', e.target.value)} placeholder="Optional" /></label>{error && <p className="admin-error" role="alert">{error}</p>}{notice && <p className="admin-success" role="status">{notice}</p>}<button className="admin-primary" type="submit" disabled={saving}>{saving ? 'Saving…' : 'Save profile'} <i className="fa-solid fa-check" /></button></form>}</section><section className="admin-panel admin-settings-card"><div className="admin-panel-heading"><div><span className="admin-overline">Workspace access</span><h3>Account security</h3></div><i className="fa-solid fa-lock admin-panel-link-icon" /></div><div className="admin-setting-row"><span>Access level</span><strong>Administrator</strong></div><div className="admin-setting-row"><span>Authentication</span><strong>Supabase Auth</strong></div><p className="admin-muted">Your administrator access is verified on the server for every protected admin page and action.</p><Link href="/account" className="admin-secondary">Open account workspace <i className="fa-solid fa-arrow-right" /></Link></section></div></AdminLayout>;
}
