import Link from 'next/link';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import AdminLayout from '../../../components/AdminLayout';
import { requireAdmin } from '../../../lib/adminAuth';

const statuses = ['NEW', 'READ', 'IN_PROGRESS', 'QUOTED', 'RESOLVED'];
export async function getServerSideProps({ req, res }) { const auth = await requireAdmin(req, res); if (!auth.ok) return { redirect: { destination: auth.status === 401 ? '/signin?next=/admin/quotes' : '/admin/quotes', permanent: false } }; return { props: {} }; }

export default function QuoteDetailPage() {
  const router = useRouter(); const [quote, setQuote] = useState(null); const [status, setStatus] = useState('NEW'); const [reply, setReply] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { if (!router.query.id) return; fetch(`/api/admin/quotes/${router.query.id}`).then(async r => { const data = await r.json(); if (!r.ok) throw new Error(data.error); setQuote(data.quote); setStatus(data.quote.status); setReply(data.quote.admin_reply || ''); }).catch(e => setError(e.message)); }, [router.query.id]);
  async function save(event) { event.preventDefault(); setSaving(true); setError(''); try { const r = await fetch(`/api/admin/quotes/${router.query.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status, adminReply: reply }) }); const data = await r.json(); if (!r.ok) throw new Error(data.error); setQuote(data.quote); } catch (e) { setError(e.message); } finally { setSaving(false); } }
  if (!quote) return <AdminLayout title="Quote request" description="Loading quote request…">{error && <p className="admin-error">{error}</p>}</AdminLayout>;
  return <AdminLayout title="Quote request" description="Review the request details and update its workflow status."><div className="admin-detail-actions"><Link className="admin-secondary" href="/admin/quotes">Back to quotes</Link></div><div className="admin-detail-grid"><section className="admin-card"><p className="admin-kicker">Request details</p>{[['Customer', quote.full_name], ['Email', quote.email], ['Phone', quote.phone], ['Company', quote.company || '—'], ['Service', quote.service_type], ['Weight', quote.weight], ['Pickup date', quote.pickup_date], ['Route', `${quote.origin_city}, ${quote.origin_state} → ${quote.destination_city}, ${quote.destination_state}`]].map(([label, value]) => <div className="admin-detail-row" key={label}><span>{label}</span><strong>{value}</strong></div>)}<p className="admin-message-body">{quote.description || 'No shipment description supplied.'}{quote.notes ? `\n\nNotes: ${quote.notes}` : ''}</p></section><section className="admin-card"><p className="admin-kicker">Workflow</p><form onSubmit={save} className="admin-form-compact"><label className="admin-field"><span>Status</span><select value={status} onChange={e => setStatus(e.target.value)}>{statuses.map(value => <option key={value}>{value}</option>)}</select></label><label className="admin-field"><span>Internal response</span><textarea rows="7" value={reply} onChange={e => setReply(e.target.value)} placeholder="Store an internal note about this request…" /></label>{error && <p className="admin-error">{error}</p>}<button className="admin-primary" type="submit" disabled={saving}>{saving ? 'Saving…' : 'Save changes'}</button></form></section></div></AdminLayout>;
}
