import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import AdminLayout from '../../../components/AdminLayout';
import { requireAdmin } from '../../../lib/adminAuth';

export async function getServerSideProps({ req, res }) {
  const auth = await requireAdmin(req, res);
  if (!auth.ok) return { redirect: { destination: auth.status === 401 ? '/signin?next=/admin/shipments' : '/admin', permanent: false } };
  return { props: {} };
}

export default function ShipmentsPage() {
  const [shipments, setShipments] = useState([]); const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [selectedShipment, setSelectedShipment] = useState(null); const [deleting, setDeleting] = useState(false);
  useEffect(() => { fetch('/api/admin/shipments').then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.error); setShipments(data.shipments || []); }).catch((err) => setError(err.message)); }, []);
  const deleteShipment = async () => { if (!selectedShipment) return; setDeleting(true); setError(''); setSuccess(''); try { const response = await fetch(`/api/admin/shipments/${selectedShipment.id}`, { method: 'DELETE' }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Unable to delete shipment. Please try again.'); setShipments((current) => current.filter((shipment) => shipment.id !== selectedShipment.id)); setSelectedShipment(null); setSuccess('Shipment deleted successfully.'); } catch (err) { setError(err.message || 'Unable to delete shipment. Please try again.'); } finally { setDeleting(false); } };
  const filtered = useMemo(() => shipments.filter((shipment) => (!search || shipment.tracking_number.toLowerCase().includes(search.toLowerCase())) && (!status || shipment.status_code === status)), [shipments, search, status]);
  return <AdminLayout title="Shipments" description="Live shipment records from Supabase."><div className="admin-toolbar"><input placeholder="Search tracking number" value={search} onChange={(event) => setSearch(event.target.value)} /><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">All statuses</option>{['BOOKED', 'PICKED_UP', 'IN_TRANSIT', 'ARRIVED', 'ON_HOLD', 'OUT_FOR_DELIVERY', 'DELIVERED'].map((item) => <option key={item} value={item}>{item.replaceAll('_', ' ')}</option>)}</select><Link className="admin-primary" href="/admin/shipments/new">Create shipment</Link></div>{error && <p className="admin-error">{error}</p>}{success && <p className="admin-success">{success}</p>}<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Tracking number</th><th>Customer</th><th>Origin</th><th>Destination</th><th>Current location</th><th>Status</th><th>Estimated delivery</th><th>Updated</th><th>Actions</th></tr></thead><tbody>{filtered.map((shipment) => <tr key={shipment.id}><td><Link href={`/admin/shipments/${shipment.id}`}>{shipment.tracking_number}</Link></td><td>{shipment.customer_name || '—'}</td><td>{shipment.origin || '—'}</td><td>{shipment.destination || '—'}</td><td>{shipment.current_location || '—'}</td><td><span className="admin-status">{shipment.status_code}</span></td><td>{shipment.estimated_delivery || '—'}</td><td>{shipment.updated_at ? new Date(shipment.updated_at).toLocaleDateString() : '—'}</td><td><button type="button" className="admin-delete-button" onClick={() => { setError(''); setSuccess(''); setSelectedShipment(shipment); }}>Delete</button></td></tr>)}</tbody></table>{!filtered.length && !error && <p className="admin-empty">No shipments found.</p>}</div>{selectedShipment && <div className="admin-modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget && !deleting) setSelectedShipment(null); }}><section className="admin-modal" role="dialog" aria-modal="true" aria-labelledby="delete-shipment-title"><h2 id="delete-shipment-title">Delete Shipment?</h2><p>This will permanently delete this shipment and its tracking history. This action cannot be undone.</p><div className="admin-modal-tracking"><span>Tracking Number:</span><strong>{selectedShipment.tracking_number}</strong></div><div className="admin-modal-actions"><button type="button" className="admin-secondary" onClick={() => setSelectedShipment(null)} disabled={deleting}>Cancel</button><button type="button" className="admin-delete-confirm" onClick={deleteShipment} disabled={deleting}>{deleting ? 'Deleting...' : 'Delete Shipment'}</button></div></section></div>}</AdminLayout>;
}
